# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource-files/main.ui'
#
# Created: Wed Apr 16 15:02:18 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DCWindow(object):
    def setupUi(self, DCWindow):
        DCWindow.setObjectName(_fromUtf8("DCWindow"))
        DCWindow.resize(849, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cpu.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DCWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(DCWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.visual = DCRegisterView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual.sizePolicy().hasHeightForWidth())
        self.visual.setSizePolicy(sizePolicy)
        self.visual.setMinimumSize(QtCore.QSize(500, 300))
        self.visual.setMaximumSize(QtCore.QSize(500, 300))
        self.visual.setObjectName(_fromUtf8("visual"))
        self.verticalLayout_3.addWidget(self.visual)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.history = QtGui.QPlainTextEdit(self.centralwidget)
        self.history.setReadOnly(True)
        self.history.setPlainText(_fromUtf8(""))
        self.history.setObjectName(_fromUtf8("history"))
        self.verticalLayout.addWidget(self.history)
        self.command = QtGui.QLineEdit(self.centralwidget)
        self.command.setObjectName(_fromUtf8("command"))
        self.verticalLayout.addWidget(self.command)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.registerGroup = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans Mono"))
        self.registerGroup.setFont(font)
        self.registerGroup.setFlat(False)
        self.registerGroup.setCheckable(False)
        self.registerGroup.setObjectName(_fromUtf8("registerGroup"))
        self.formLayout = QtGui.QFormLayout(self.registerGroup)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelAC = QtGui.QLabel(self.registerGroup)
        self.labelAC.setObjectName(_fromUtf8("labelAC"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelAC)
        self.valueAC = QtGui.QLabel(self.registerGroup)
        self.valueAC.setObjectName(_fromUtf8("valueAC"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.valueAC)
        self.labelDR = QtGui.QLabel(self.registerGroup)
        self.labelDR.setObjectName(_fromUtf8("labelDR"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDR)
        self.valueDR = QtGui.QLabel(self.registerGroup)
        self.valueDR.setObjectName(_fromUtf8("valueDR"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.valueDR)
        self.labelAR = QtGui.QLabel(self.registerGroup)
        self.labelAR.setObjectName(_fromUtf8("labelAR"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelAR)
        self.valueAR = QtGui.QLabel(self.registerGroup)
        self.valueAR.setObjectName(_fromUtf8("valueAR"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.valueAR)
        self.labelPC = QtGui.QLabel(self.registerGroup)
        self.labelPC.setObjectName(_fromUtf8("labelPC"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelPC)
        self.valuePC = QtGui.QLabel(self.registerGroup)
        self.valuePC.setObjectName(_fromUtf8("valuePC"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.valuePC)
        self.labelSP = QtGui.QLabel(self.registerGroup)
        self.labelSP.setObjectName(_fromUtf8("labelSP"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelSP)
        self.valueSP = QtGui.QLabel(self.registerGroup)
        self.valueSP.setObjectName(_fromUtf8("valueSP"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.valueSP)
        self.labelBP = QtGui.QLabel(self.registerGroup)
        self.labelBP.setObjectName(_fromUtf8("labelBP"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelBP)
        self.valueBP = QtGui.QLabel(self.registerGroup)
        self.valueBP.setObjectName(_fromUtf8("valueBP"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.valueBP)
        self.horizontalLayout_2.addWidget(self.registerGroup)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.RAM = QtGui.QListView(self.centralwidget)
        self.RAM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans Mono"))
        self.RAM.setFont(font)
        self.RAM.setObjectName(_fromUtf8("RAM"))
        self.horizontalLayout_4.addWidget(self.RAM)
        DCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        DCWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DCWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DCWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DCWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DCWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRun = QtGui.QAction(DCWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon1)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionStep = QtGui.QAction(DCWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/step.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep.setIcon(icon2)
        self.actionStep.setObjectName(_fromUtf8("actionStep"))
        self.actionStop = QtGui.QAction(DCWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionOpen = QtGui.QAction(DCWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClear = QtGui.QAction(DCWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon5)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(DCWindow)
        QtCore.QMetaObject.connectSlotsByName(DCWindow)

    def retranslateUi(self, DCWindow):
        DCWindow.setWindowTitle(_translate("DCWindow", "DC reloaded", None))
        self.registerGroup.setTitle(_translate("DCWindow", "Register", None))
        self.labelAC.setToolTip(_translate("DCWindow", "Accumulator", None))
        self.labelAC.setText(_translate("DCWindow", "AC =", None))
        self.valueAC.setText(_translate("DCWindow", "    0", None))
        self.labelDR.setToolTip(_translate("DCWindow", "Data Register", None))
        self.labelDR.setText(_translate("DCWindow", "DR =", None))
        self.valueDR.setText(_translate("DCWindow", "    0", None))
        self.labelAR.setToolTip(_translate("DCWindow", "Address Register", None))
        self.labelAR.setText(_translate("DCWindow", "AR =", None))
        self.valueAR.setText(_translate("DCWindow", "    0", None))
        self.labelPC.setToolTip(_translate("DCWindow", "Program Counter", None))
        self.labelPC.setText(_translate("DCWindow", "PC =", None))
        self.valuePC.setText(_translate("DCWindow", "    0", None))
        self.labelSP.setToolTip(_translate("DCWindow", "Stack Pointer", None))
        self.labelSP.setText(_translate("DCWindow", "SP =", None))
        self.valueSP.setText(_translate("DCWindow", "  127", None))
        self.labelBP.setToolTip(_translate("DCWindow", "Base Pointer", None))
        self.labelBP.setText(_translate("DCWindow", "BP =", None))
        self.valueBP.setText(_translate("DCWindow", "  127", None))
        self.toolBar.setWindowTitle(_translate("DCWindow", "toolBar", None))
        self.actionRun.setText(_translate("DCWindow", "Run", None))
        self.actionRun.setToolTip(_translate("DCWindow", "Run the current script", None))
        self.actionRun.setShortcut(_translate("DCWindow", "Ctrl+R", None))
        self.actionStep.setText(_translate("DCWindow", "Step", None))
        self.actionStep.setToolTip(_translate("DCWindow", "One step forward", None))
        self.actionStep.setShortcut(_translate("DCWindow", "Ctrl+S", None))
        self.actionStop.setText(_translate("DCWindow", "Stop", None))
        self.actionStop.setToolTip(_translate("DCWindow", "Stops the execution", None))
        self.actionStop.setShortcut(_translate("DCWindow", "Ctrl+Esc", None))
        self.actionOpen.setText(_translate("DCWindow", "Open", None))
        self.actionOpen.setToolTip(_translate("DCWindow", "Open a file", None))
        self.actionOpen.setShortcut(_translate("DCWindow", "Ctrl+O", None))
        self.actionClear.setText(_translate("DCWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("DCWindow", "Clear everything", None))
        self.actionClear.setShortcut(_translate("DCWindow", "Ctrl+C", None))

from dc.interface.registerview import DCRegisterView
from . import resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DCWindow = QtGui.QMainWindow()
    ui = Ui_DCWindow()
    ui.setupUi(DCWindow)
    DCWindow.show()
    sys.exit(app.exec_())

