# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource-files/main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DCWindow(object):
    def setupUi(self, DCWindow):
        DCWindow.setObjectName("DCWindow")
        DCWindow.resize(849, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DCWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.visual = DCRegisterView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual.sizePolicy().hasHeightForWidth())
        self.visual.setSizePolicy(sizePolicy)
        self.visual.setMinimumSize(QtCore.QSize(500, 300))
        self.visual.setMaximumSize(QtCore.QSize(500, 300))
        self.visual.setObjectName("visual")
        self.verticalLayout_3.addWidget(self.visual)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.history = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.history.setReadOnly(True)
        self.history.setPlainText("")
        self.history.setObjectName("history")
        self.verticalLayout.addWidget(self.history)
        self.command = QtWidgets.QLineEdit(self.centralwidget)
        self.command.setObjectName("command")
        self.verticalLayout.addWidget(self.command)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.registerGroup = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.registerGroup.setFont(font)
        self.registerGroup.setFlat(False)
        self.registerGroup.setCheckable(False)
        self.registerGroup.setObjectName("registerGroup")
        self.formLayout = QtWidgets.QFormLayout(self.registerGroup)
        self.formLayout.setObjectName("formLayout")
        self.labelAC = QtWidgets.QLabel(self.registerGroup)
        self.labelAC.setObjectName("labelAC")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAC)
        self.valueAC = QtWidgets.QLabel(self.registerGroup)
        self.valueAC.setObjectName("valueAC")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.valueAC)
        self.labelDR = QtWidgets.QLabel(self.registerGroup)
        self.labelDR.setObjectName("labelDR")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelDR)
        self.valueDR = QtWidgets.QLabel(self.registerGroup)
        self.valueDR.setObjectName("valueDR")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.valueDR)
        self.labelAR = QtWidgets.QLabel(self.registerGroup)
        self.labelAR.setObjectName("labelAR")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelAR)
        self.valueAR = QtWidgets.QLabel(self.registerGroup)
        self.valueAR.setObjectName("valueAR")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.valueAR)
        self.labelPC = QtWidgets.QLabel(self.registerGroup)
        self.labelPC.setObjectName("labelPC")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelPC)
        self.valuePC = QtWidgets.QLabel(self.registerGroup)
        self.valuePC.setObjectName("valuePC")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.valuePC)
        self.labelSP = QtWidgets.QLabel(self.registerGroup)
        self.labelSP.setObjectName("labelSP")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelSP)
        self.valueSP = QtWidgets.QLabel(self.registerGroup)
        self.valueSP.setObjectName("valueSP")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.valueSP)
        self.labelBP = QtWidgets.QLabel(self.registerGroup)
        self.labelBP.setObjectName("labelBP")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelBP)
        self.valueBP = QtWidgets.QLabel(self.registerGroup)
        self.valueBP.setObjectName("valueBP")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.valueBP)
        self.horizontalLayout_2.addWidget(self.registerGroup)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.RAM = QtWidgets.QListView(self.centralwidget)
        self.RAM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.RAM.setFont(font)
        self.RAM.setObjectName("RAM")
        self.horizontalLayout_4.addWidget(self.RAM)
        DCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 19))
        self.menubar.setObjectName("menubar")
        DCWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DCWindow)
        self.statusbar.setObjectName("statusbar")
        DCWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DCWindow)
        self.toolBar.setObjectName("toolBar")
        DCWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRun = QtWidgets.QAction(DCWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon1)
        self.actionRun.setObjectName("actionRun")
        self.actionStep = QtWidgets.QAction(DCWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/step.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep.setIcon(icon2)
        self.actionStep.setObjectName("actionStep")
        self.actionStop = QtWidgets.QAction(DCWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionOpen = QtWidgets.QAction(DCWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClear = QtWidgets.QAction(DCWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon5)
        self.actionClear.setObjectName("actionClear")
        self.actionHelp = QtWidgets.QAction(DCWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave = QtWidgets.QAction(DCWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName("actionSave")
        self.actionEditor = QtWidgets.QAction(DCWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditor.setIcon(icon8)
        self.actionEditor.setObjectName("actionEditor")
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionEditor)

        self.retranslateUi(DCWindow)
        QtCore.QMetaObject.connectSlotsByName(DCWindow)

    def retranslateUi(self, DCWindow):
        _translate = QtCore.QCoreApplication.translate
        DCWindow.setWindowTitle(_translate("DCWindow", "DC reloaded"))
        self.registerGroup.setTitle(_translate("DCWindow", "Register"))
        self.labelAC.setToolTip(_translate("DCWindow", "Accumulator"))
        self.labelAC.setText(_translate("DCWindow", "AC ="))
        self.valueAC.setText(_translate("DCWindow", "    0"))
        self.labelDR.setToolTip(_translate("DCWindow", "Data Register"))
        self.labelDR.setText(_translate("DCWindow", "DR ="))
        self.valueDR.setText(_translate("DCWindow", "    0"))
        self.labelAR.setToolTip(_translate("DCWindow", "Address Register"))
        self.labelAR.setText(_translate("DCWindow", "AR ="))
        self.valueAR.setText(_translate("DCWindow", "    0"))
        self.labelPC.setToolTip(_translate("DCWindow", "Program Counter"))
        self.labelPC.setText(_translate("DCWindow", "PC ="))
        self.valuePC.setText(_translate("DCWindow", "    0"))
        self.labelSP.setToolTip(_translate("DCWindow", "Stack Pointer"))
        self.labelSP.setText(_translate("DCWindow", "SP ="))
        self.valueSP.setText(_translate("DCWindow", "  127"))
        self.labelBP.setToolTip(_translate("DCWindow", "Base Pointer"))
        self.labelBP.setText(_translate("DCWindow", "BP ="))
        self.valueBP.setText(_translate("DCWindow", "  127"))
        self.toolBar.setWindowTitle(_translate("DCWindow", "toolBar"))
        self.actionRun.setText(_translate("DCWindow", "Run"))
        self.actionRun.setToolTip(_translate("DCWindow", "Run the current script"))
        self.actionRun.setShortcut(_translate("DCWindow", "Ctrl+R"))
        self.actionStep.setText(_translate("DCWindow", "Step"))
        self.actionStep.setToolTip(_translate("DCWindow", "One step forward"))
        self.actionStep.setShortcut(_translate("DCWindow", "Ctrl+S"))
        self.actionStop.setText(_translate("DCWindow", "Stop"))
        self.actionStop.setToolTip(_translate("DCWindow", "Stops the execution"))
        self.actionStop.setShortcut(_translate("DCWindow", "Ctrl+Esc"))
        self.actionOpen.setText(_translate("DCWindow", "Open"))
        self.actionOpen.setToolTip(_translate("DCWindow", "Open a file"))
        self.actionOpen.setShortcut(_translate("DCWindow", "Ctrl+O"))
        self.actionClear.setText(_translate("DCWindow", "Clear"))
        self.actionClear.setToolTip(_translate("DCWindow", "Clear everything"))
        self.actionClear.setShortcut(_translate("DCWindow", "Ctrl+C"))
        self.actionHelp.setText(_translate("DCWindow", "Help"))
        self.actionHelp.setToolTip(_translate("DCWindow", "Open the documentation in a browser"))
        self.actionHelp.setShortcut(_translate("DCWindow", "F1"))
        self.actionSave.setText(_translate("DCWindow", "Save"))
        self.actionSave.setToolTip(_translate("DCWindow", "Save the current RAM as a file"))
        self.actionEditor.setText(_translate("DCWindow", "Editor"))
        self.actionEditor.setToolTip(_translate("DCWindow", "Open the script editor"))
        self.actionEditor.setShortcut(_translate("DCWindow", "Ctrl+E"))

from dc.interface.registerview import DCRegisterView
from . import resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DCWindow = QtWidgets.QMainWindow()
    ui = Ui_DCWindow()
    ui.setupUi(DCWindow)
    DCWindow.show()
    sys.exit(app.exec_())

